# golangci-lint 配置文件
# 系統設計專案：確保代碼質量和最佳實踐
#
# 設計理念：
#   - 教學導向：註解清晰、代碼優雅
#   - 安全優先：防止常見漏洞（SSRF、SQL 注入等）
#   - 性能意識：避免常見性能陷阱
#   - 可維護性：遵循 Go 最佳實踐

run:
  # 超時設置（大型項目需要更長時間）
  timeout: 10m

  # Go 版本
  go: '1.24'

  # 跳過的目錄
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - _tools

  # 跳過的文件
  skip-files:
    - ".*\\.pb\\.go$"  # protobuf 生成的文件
    - ".*_gen\\.go$"    # 生成的文件

# Linter 配置
linters:
  # 啟用所有 linter（然後選擇性禁用）
  enable-all: false

  # 明確啟用的 linter
  enable:
    # === 基礎檢查 ===
    - errcheck      # 檢查未處理的錯誤
    - gosimple      # 簡化代碼建議
    - govet         # Go 官方 vet 工具
    - ineffassign   # 檢測無效賦值
    - staticcheck   # 靜態分析（非常重要）
    - unused        # 檢查未使用的代碼
    - typecheck     # 類型檢查

    # === 代碼風格 ===
    - gofmt         # 格式化檢查
    - goimports     # import 整理
    - misspell      # 拼寫錯誤
    - whitespace    # 空白字符檢查

    # === 性能優化 ===
    - prealloc      # slice 預分配
    - unconvert     # 不必要的類型轉換

    # === 安全檢查 ===
    - gosec         # 安全漏洞掃描（G1xx 系列）

    # === 代碼複雜度 ===
    - gocyclo       # 圈複雜度
    - gocognit      # 認知複雜度
    - funlen        # 函數長度

    # === 錯誤處理 ===
    - errorlint     # 錯誤處理最佳實踐
    - wrapcheck     # 錯誤包裝檢查

    # === 並發安全 ===
    - gocritic      # Go 代碼審查
    - rowserrcheck  # SQL rows.Err() 檢查
    - sqlclosecheck # SQL Close() 檢查

    # === 註解檢查 ===
    - godot         # 註解句號檢查
    - revive        # 快速、可配置的 linter

    # === 命名規範 ===
    - stylecheck    # 命名風格檢查

  # 禁用的 linter（說明原因）
  disable:
    - exhaustruct   # 要求結構體初始化所有字段（教學項目太嚴格）
    - nlreturn      # 返回前空行要求（風格偏好）
    - wsl           # 空白行強制規則（過於嚴格）
    - exhaustive    # 窮舉 switch（某些場景不適用）
    - forcetypeassert # 強制類型斷言檢查（教學代碼簡化）
    - varnamelen    # 變量名長度（短變量名在某些場景下更清晰）

# Linter 具體設置
linters-settings:
  # === errcheck：錯誤檢查 ===
  errcheck:
    check-type-assertions: true  # 檢查類型斷言
    check-blank: true            # 檢查 _ = err

  # === govet：Go 官方工具 ===
  govet:
    enable-all: true
    disable:
      - shadow  # 變量遮蔽（教學代碼允許）

  # === gocyclo：圈複雜度 ===
  gocyclo:
    min-complexity: 15  # 最大圈複雜度

  # === gocognit：認知複雜度 ===
  gocognit:
    min-complexity: 20  # 認知複雜度閾值

  # === funlen：函數長度 ===
  funlen:
    lines: 100        # 函數最大行數
    statements: 50    # 函數最大語句數

  # === gosec：安全檢查 ===
  gosec:
    severity: medium
    confidence: medium
    excludes:
      # G104: 某些錯誤可以忽略（如 Close()）
      # - G104  # 保持啟用，確保錯誤處理

  # === gocritic：代碼審查 ===
  gocritic:
    enabled-checks:
      - ruleguard
      - truncateCmp
    disabled-checks:
      - ifElseChain      # if-else 鏈（教學代碼更清晰）
      - singleCaseSwitch # 單個 case 的 switch（某些場景更清晰）

  # === revive：快速 linter ===
  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  # === stylecheck：命名風格 ===
  stylecheck:
    checks: ["all", "-ST1003"]  # 禁用駝峰命名檢查（某些縮寫）

  # === misspell：拼寫檢查 ===
  misspell:
    locale: US

  # === wrapcheck：錯誤包裝 ===
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

# Issue 配置
issues:
  # 排除規則
  exclude-rules:
    # 測試文件放寬限制
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
        - dupl
        - gosec

    # 主函數（main.go）放寬限制
    - path: cmd/server/main\.go
      linters:
        - funlen

    # 生成的代碼跳過
    - path: ".*_gen\\.go"
      linters:
        - all

  # 最大問題數量（0 = 無限制）
  max-issues-per-linter: 0
  max-same-issues: 0

  # 顯示所有問題（不截斷）
  exclude-use-default: false

# 輸出配置
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

# 嚴重性設置
severity:
  default-severity: warning
  rules:
    - linters:
        - gosec
        - errcheck
      severity: error
